# Generated by Django 2.0.8 on 2018-08-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.IntegerField(primary_key=True, serialize=False, verbose_name='usuario')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('email', models.CharField(max_length=60, verbose_name='email')),
                ('password', models.CharField(max_length=30, verbose_name='senha')),
            ],
            options={
                'verbose_name_plural': 'usuarios',
                'verbose_name': 'usuario',
            },
        ),
    ]
