# Generated by Django 2.0.8 on 2018-08-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('sugges', models.IntegerField(primary_key=True, serialize=False, verbose_name='proposta')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('description', models.TextField(verbose_name='descrição')),
                ('result', models.CharField(max_length=150, verbose_name='resultado')),
            ],
            options={
                'verbose_name_plural': 'propostas',
                'verbose_name': 'prposta',
            },
        ),
    ]
