# Generated by Django 2.0.8 on 2018-08-19 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vota', '0003_auto_20180819_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='identificacao')),
                ('kind', models.CharField(max_length=150, verbose_name='tipo')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_suggestion', to='vota.Suggestion', verbose_name='comentário')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_user', to='vota.User', verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'votos',
                'verbose_name_plural': 'votos',
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='suggestion',
        ),
        migrations.AddField(
            model_name='comment',
            name='sugges',
            field=models.ForeignKey(default='suggestion', on_delete=django.db.models.deletion.CASCADE, related_name='id_sugges', to='vota.Suggestion', verbose_name='comentário'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_user', to='vota.User', verbose_name='usuário'),
        ),
    ]
