# Generated by Django 2.0.8 on 2018-08-19 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vota', '0004_auto_20180819_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='sugges',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_sugges', to='vota.Suggestion', verbose_name='comentário'),
        ),
    ]
