# Generated by Django 2.0.8 on 2018-08-19 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vota', '0008_auto_20180819_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='sugges',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='id_sugges', to='vota.Suggestion', verbose_name='comentário'),
        ),
    ]
