# Generated by Django 2.0.8 on 2018-08-19 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vota', '0009_auto_20180819_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='sugges',
        ),
        migrations.AddField(
            model_name='comment',
            name='suggestion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sugges', to='vota.Suggestion', verbose_name='comentário'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='vota.User', verbose_name='usuário'),
        ),
    ]
